routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('comments', 'CommentController');
Route::get('/', 'PageController@index');

Route::get('/info/{id}', 'GeneralPagesController@show')->name('general');
Route::post('/authenticate', 'GeneralPagesController@authenticate')->name('manual_auth');

Auth::routes();

Route::get('/redirect', 'SocialAuthFacebookController@redirect')
  ->name('fb_login');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::resource('pages', 'PageController');
Route::resource('orders', 'OrderController');
Route::resource('pages.coupons', 'CouponController',
  ['only' => ['index', 'show']]
);
Route::post('/add-to-cart', 'CartController@addToCart')
  ->name('add-to-cart');
Route::post('/remove-from-cart', 'CartController@removeFromCart')
  ->name('remove-from-cart');
  Route::get('/cart', 'CartController@index')
    ->name('cart');
Route::post('/coupon_used', 'CouponController@coupon_used')->name('use_coupon');
Route::post('/social_store', 'SocialAuthFacebookController@saveSocialUser')->name('social_store');
Route::get('/social_create', 'SocialAuthFacebookController@createSocialUser')->name('create-social-user');

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CartController extends Controller
{

    public function index()
    {
      $summary = 0;
      foreach ((array)session('cart') as $k => $v) {
        $summary += \App\Coupon::find($k)->price * $v;
      }
      return view('cart.index')
        ->with('summary', $summary);
    }

    public function addToCart(Request $request)
    {
        $cart = (array)session('cart');
        $id = $request->get('product_id');
        $count = $request->get('count');
        if (key_exists($id, $cart)){
          $count = $cart[$id] + $count;
        }
        $cart[$id] = $count;
        session(['cart' => $cart]);
        return response()
          ->json(['status'=>'success']);
    }

    public function removeFromCart(Request $request)
    {
        $cart = (array)session('cart');
        $id = $request->get('product_id');
        if (key_exists($id, $cart)){
          unset($cart[$id]);
        }
        session(['cart' => $cart]);
        return response()
          ->json(['status'=>'success']);
    }

    public function getCart()
    {
        $cart = (array)session('cart');
    }

}

resources/views/cart/index.blade.php
@extends('layouts.app')
@section('content')
  <h1 class='header-title-main'>Cart</h1>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Product</th>
        <th>Count</th>
        <th>Summary</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      @foreach ((array)session('cart') as $key => $val)
        <tr>
          <td>{{ \App\Coupon::find($key)->title }}</td>
          <td>{{ $val}}</td>
          <td>{{ \App\Coupon::find($key)->price * $val .'$'}}</td>
          <td>
            <button
              class="btn btn-danger"
              onclick="handleRemove(this,{{ \App\Coupon::find($key)->id }})"
            >X</button>
          </td>
        </tr>
      @endforeach
      @if(count((array)session('cart'))>0)
        <tr>
          <td> Summary </td>
          <td>{{ $summary.'$' }}</td>
          <td>
            <a href="{{ route('orders.create')}}" class='btn btn-success'> Process</a>
          </td>
        </tr>
      @endif
    </tbody>

  </table>
  <script type="text/javascript">
    function handleRemove(event, id){
      console.log('clicked');
        $.ajax({
          method: "POST",
          url: "{{ route('remove-from-cart')}}",
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          data: { product_id: id }
        })
      .done(function( response ) {
        location.reload();
      });
    }
  </script>
@endsection