routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('comments', 'CommentController');
Route::get('/', 'PageController@index');

Route::get('/info/{id}', 'GeneralPagesController@show')->name('general');
Route::post('/authenticate', 'GeneralPagesController@authenticate')->name('manual_auth');

Auth::routes();

Route::get('/redirect', 'SocialAuthFacebookController@redirect')
  ->name('fb_login');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::resource('pages', 'PageController');
Route::resource('orders', 'OrderController');
Route::resource('pages.coupons', 'CouponController',
  ['only' => ['index', 'show']]
);
Route::post('/add-to-cart', 'CartController@addToCart')
  ->name('add-to-cart');
Route::post('/remove-from-cart', 'CartController@removeFromCart')
  ->name('remove-from-cart');
  Route::get('/cart', 'CartController@index')
    ->name('cart');
Route::post('/coupon_used', 'CouponController@coupon_used')->name('use_coupon');
Route::post('/social_store', 'SocialAuthFacebookController@saveSocialUser')->name('social_store');
Route::get('/social_create', 'SocialAuthFacebookController@createSocialUser')->name('create-social-user');

resources/views/shared/comment-form.blade.php
<div class="new-comment">
  <h2 class='comments-title'>ADD NEW COMMENT</h2>
  <form class="" action="{{ route('comments.store')}}" method="post">
    {{ csrf_field() }}
    <input type="hidden" name="coupon_id" value="{{ $coupon->id }}">
    <div class="form-group">
      <textarea name="text" rows="3" cols="30" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <input type="submit" name="" class="btn btn-success" value="Add comment">
    </div>
  </form>
</div>

resources/views/shared/coupon-preview.blade.php
<div class="coupon-preview">
  <div class="preview-logo">
    <div class="logo-overfloww"></div>
    {{-- <img src="{{ Storage::url($coupon->image)}}" alt="" > --}}
    <img src="{{ $coupon->image }}" alt="" >
  </div>
  <div class="preview-text">
    <a href="{{ route('pages.coupons.show', [$page->slug, $coupon->slug])}}"><h3>{{ $coupon->title}}</h3>
    <p>{{ $coupon->note}}</p>
    </a>
  </div>
</div>

resources/views/shared/dropdown.blade.php
<div class="dropdown drop-menu-block">
  <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
    <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
  <ul class="dropdown-menu dropdown-nav-item">
    <li><a href="/">Home</a></li>
    <li class="divider"></li>
    @foreach ($pages as $page)
      <li>
        <a href={{ route('pages.show', ['id' => $page->slug])}}>
          {{ $page->topic }}
        </a>
      </li>
      <li class="divider"></li>
    @endforeach
  </ul>
</div>

resources/views/shared/footer.blade.php
<div class="footer">
  <div class="footer-content">
    <div class="company-logo">
      <img src="http://clipart-library.com/image_gallery2/Globe-PNG.png" alt="" >
      <p class="company-name">{{ $_settings->company or 'company'}}</p>
    </div>
    <div class="footer-items">
      <div class="footer-item">
        <h2>{{ $_settings->footer_general_title or 'footer_general_title'}}</h2>
        <ul>
          @include('shared.main_nav')
        </ul>
      </div>
      <div class="footer-item">
        <h2>{{ $_settings->footer_categories_title or 'footer_categories_title'}}</h2>

        @foreach ($pages as $page)
          <li>
            <a href={{ route('pages.show', ['id' => $page->slug])}}>
              {{ ucfirst($page->topic) }}
            </a>
          </li>
        @endforeach
      </div>
    </div>
  </div>
  <div class="footer-copyrights">
    <h4>{{ $_settings->footer_rights or 'footer_rights'}}</h4>
  </div>
</div>

resources/views/shared/header-static.blade.php
<div class="header" id="header">
  <div class="header-lang">
    <div class="nav-sm-left">
      <div class="nav-links">
        <nav class="header-nav">
          <ul>
            @guest
              <li><a href="{{ route('fb_login')}}" class="facebook-link"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="{{ route('login')}}" class="login-link"><i class="fa fa-user" aria-hidden="true"></i></a></li>
              <li><a href="{{ route('register') }}" class="logout-link"><i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
            @else
              <li>
                  <a href="{{ route('logout') }}"
                      onclick="event.preventDefault();
                               document.getElementById('logout-form').submit();">
                      Logout
                  </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                  </form>
              </li>
            @endguest
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="header-content">
    <div class="header-brand">
      Store
    </div>
    <div class="header-menu">
      <a href="#" id="menu-toggle">
        <div class="header-menu-item">
          <i class="fa fa-bars" aria-hidden="true"></i>
          <h3>MENU</h3>
        </div>
      </a>
      <a href="/">
        <div class="header-menu-item">
          <i class="fa fa-home" aria-hidden="true"></i>
          <h3>HOME</h3>
        </div>
      </a>
      <a href="#">
        <div class="header-menu-item">
          <i class="fa fa-question-circle" aria-hidden="true"></i>
          <h3>ABOUT</h3>
        </div>
      </a>
      <a href="{{ route('login')}}">
        <div class="header-menu-item">
          <i class="fa fa-user" aria-hidden="true"></i>
          <h3>LOGIN</h3>
        </div>
      </a>
      <a href="{{ route('cart') }}">
        <div class="header-menu-item">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          <h3>CART {{ count((array)session('cart'))}}</h3>
        </div>
      </a>
    </div>
  </div>
</div>
<div class="">
  <div class="nav-sidebar-container close-slider" id="nav-slider">
    <div class="nav-sidebar">
      <ul>
        <li class="nav-sidebar-item">
          <a href='#' class='sidebar-close-button close-slider' id='' >
            X
          </a>
        </li>
        @foreach ($pages as $page)
          <li class="nav-sidebar-item">
            <a href="{{ route('pages.show',['pageId'=> $page->slug])}}">
              {{ $page->title }}
            </a>
          </li>
        @endforeach
      </ul>
    </div>
  </div>
</div>
<script type="text/javascript">

  window.onscroll = function() {
    var scrolled = window.pageYOffset || document.documentElement.scrollTop;
    var header = document.getElementById('header')
    var content = document.getElementById('content')
    var classList = header.classList
    if ( scrolled > 20 && !classList.contains('fixed-header')){
      header.classList.add('fixed-header');
    } else if(scrolled <= 20 && classList.contains('fixed-header')) {
      document.getElementById('header').classList.remove('fixed-header');
    }
  }
</script>

resources/views/shared/header.blade.php
<div class="header">
  <div class="nav-sm-container">
    <div class="nav-sm">
      <div class="nav-sm-right">
        <div class="nav-links">

          <nav class="header-nav">
            <ul class="drop-menu-block">
              @include('shared.dropdown')
            </ul>
            <ul class="large-menu-block">
              @include('shared.main_nav')
            </ul>
        </nav>

        </div>
      </div>
      <div class="nav-sm-left">
        <div class="nav-links">
          <nav class="header-nav">
            <ul>
              @guest
                <li><a href="{{ route('fb_login')}}" class="facebook-link"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="{{ route('login')}}" class="login-link"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                <li><a href="{{ route('register') }}" class="logout-link"><i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
              @else
                <li>
                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
              @endguest
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="nav-lg">
  <div class="nav-menu">
    <div class="large-menu-block">
      @include('shared.nav-links', ['pages', $pages])
    </div>
    <div class="nav-menu-logo">
      <img src="{{ Storage::url($_settings->logo)}}" alt="" >
    </div>
  </div>

  </div>
</div>

resources/views/shared/login-popup.blade.php
<!-- Button trigger modal -->
<button type="button" style="margin:0" class="btn btn-coupon btn-lg" data-toggle="modal" data-target="#myModal">
  JOIN US
</button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close pull-left" data-dismiss="modal" aria-hidden="true">
          <font style="vertical-align: inherit;">
            <font style="vertical-align: inherit;">×</font>
          </font>
        </button>
        <span class="modal-title">
          <font style="vertical-align: inherit;">
            <font style="vertical-align: inherit;">Login</font>
          </font>
        </span>
      </div>
      <div class="modal-body">
          <div class="sclogin sourcecoast" id="sclogin-426">
            <div class="row-fluid">
          <div class="sclogin-joomla-login vertical span12">
            <form method="POST" action="{{ route('manual_auth') }}" id="sclogin-form426">
                <fieldset class="input-block-level userdata">
                    <div class="control-group" id="form-sclogin-username">
                      <div class="controls input-block-level">
                        <div class="input-append input-block-level">
                          {{ csrf_field() }}
                          <input name="email" tabindex="0" id="sclogin-username" class="input-block-level" alt="email" type="text" placeholder="Email" >
                        </div>
                      </div>
                    </div>
                      <div class="control-group" id="form-sclogin-password">
                        <div class="controls input-block-level">
                          <div class="input-append input-block-level">
                            <input name="password" tabindex="0" id="sclogin-passwd" class="input-block-level" alt="password" type="password" placeholder="Password">
                          </div>
                        </div>
                      </div>
                      <div class="control-group" id="form-sclogin-submitcreate">
                        <button type="submit" name="Submit" class="btn btn-primary ">
                          <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">Login</font></font>
                        </button>
                      <a class="btn" href="/register">
                        <font style="vertical-align: inherit;">
                          <font style="vertical-align: inherit;">Register</font>
                        </font>
                      </a>
                    </div>
                    <input id="sclogin-remember" type="hidden" name="remember" class="inputbox" checked="checked" value="yes" alt="Запомнить меня">
                    <input type="hidden" name="option" value="com_users"><input type="hidden" name="task" value="user.login"><input type="hidden" name="return" value="aHR0cHM6Ly9qZXJ1cy5jaXR5Lw=="><input type="hidden" name="mod_id" value="426"><input type="hidden" name="1108fe6028405c68711b1cb74878c860" value="1">            </fieldset>
                  </form>
                </div>
              </div>
            <div class="clearfix"></div>
          </div>
      </div>
    </div>
  </div>
</div>

resources/views/shared/main_nav.blade.php
<li><a href="/">Home</a></li>
@foreach ($nav as $nav_item)
  <li><a href="{{ route('general', ['id'=> $nav_item->slug ])}}">
    {{ $nav_item->link_name }}
  </a></li>
@endforeach

resources/views/shared/map.blade.php
<div class="map-container">
  <div class="map-description">
    FIND ON MAP
  </div>
  <div id="coupon-map"></div>
</div>
<script>
  function initMap() {
    var uluru = {lat: {{ (float)$coupon->latitude}}, lng: {{ (float)$coupon->longitude }}};
    var mapOptions = {
      zoom: 16,
      center: uluru,
      mapOptions,
      styles: [
          {
              "featureType": "administrative",
              "elementType": "all",
              "stylers": [
                  {
                      "saturation": "-100"
                  }
              ]
          },
          {
              "featureType": "administrative.province",
              "elementType": "all",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "featureType": "landscape",
              "elementType": "all",
              "stylers": [
                  {
                      "saturation": -100
                  },
                  {
                      "lightness": 65
                  },
                  {
                      "visibility": "on"
                  }
              ]
          },
          {
              "featureType": "poi",
              "elementType": "all",
              "stylers": [
                  {
                      "saturation": -100
                  },
                  {
                      "lightness": "50"
                  },
                  {
                      "visibility": "simplified"
                  }
              ]
          },
          {
              "featureType": "road",
              "elementType": "all",
              "stylers": [
                  {
                      "saturation": "-100"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "all",
              "stylers": [
                  {
                      "visibility": "simplified"
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "all",
              "stylers": [
                  {
                      "lightness": "30"
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "all",
              "stylers": [
                  {
                      "lightness": "40"
                  }
              ]
          },
          {
              "featureType": "transit",
              "elementType": "all",
              "stylers": [
                  {
                      "saturation": -100
                  },
                  {
                      "visibility": "simplified"
                  }
              ]
          },
          {
              "featureType": "water",
              "elementType": "geometry",
              "stylers": [
                  {
                      "hue": "#ffff00"
                  },
                  {
                      "lightness": -25
                  },
                  {
                      "saturation": -97
                  }
              ]
          },
          {
              "featureType": "water",
              "elementType": "labels",
              "stylers": [
                  {
                      "lightness": -25
                  },
                  {
                      "saturation": -100
                  }
              ]
          }
      ]
    }
    var map = new google.maps.Map(document.getElementById('coupon-map'), mapOptions);

    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_API_KEY', '')}}&callback=initMap">
</script>

resources/views/shared/nav-box.blade.php
<div class="nav-slider small">
  <div class="nav-slider-title">
    <h2>CATEGORIES</h2>
  </div>
  <div class="nav-slider-text">
    <ul>
      @foreach ($pages as $page)
        <li>
          <a href="{{ route('pages.show', ['id'=> $page->slug])}}">
            <h4>
              <span>
                <i class=" {{'fa ' . $page->fa_fa_icon}}" aria-hidden="true"></i>
              </span>
              {{ $page->title }}
            </h4>
          </a>
        </li>
      @endforeach
    </ul>
  </div>
</div>

resources/views/shared/nav-links.blade.php
@foreach ($pages as $page)
  <a href="{{ route('pages.show', ['id' => $page->slug])}}" class="menu-item-link">
    <div class="menu-item">
        {{ strtoupper($page->topic) }}
    </div>
  </a>
@endforeach

resources/views/shared/nav-slider-large.blade.php
<div class="inner-nav-menu">
  <a href="#">
    <div class="inner-nav-content">
      <i class="fa fa-th-large" aria-hidden="true"></i>
      <h3>
        Citizens
      </h3>
    </div>
  </a>
  <a href="#">
    <div class="inner-nav-content">
      <i class="fa fa-th-large" aria-hidden="true"></i>
      <h3>
        Students
      </h3>
    </div>
  </a>
  <a href="#">
    <div class="inner-nav-content">
      <i class="fa fa-th-large" aria-hidden="true"></i>
      <h3>
        Old mans
      </h3>
    </div>
  </a>
  <a href="#">
    <div class="inner-nav-content">
      <i class="fa fa-th-large" aria-hidden="true"></i>
      <h3>
        Immigrants
      </h3>
    </div>
  </a>
  <a href="#">
    <div class="inner-nav-content">
      <i class="fa fa-th-large" aria-hidden="true"></i>
      <h3>
        Another Peoples
      </h3>
    </div>
  </a>
</div>

resources/views/shared/nav-slider.blade.php
<div class="nav-slider small">
  <div class="nav-slider-text">
    @foreach ($info_pages as $info)
      <a href="{{ route('general', ['id' => $info->slug])}}" class="nav-slider-link">
        <div class="nav-slider-item">
          <div class="slider-icon">
            <i class="fa {{ $info->fa_fa_icon}}" aria-hidden="true"></i>
          </div>
          <h4>
            {{ $info->title }}
          </h4>
          <p>
            {{ $info->preview_text }}
          </p>
        </div>
      </a>
    @endforeach
  </div>
</div>