routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('comments', 'CommentController');
Route::get('/', 'PageController@index');

Route::get('/info/{id}', 'GeneralPagesController@show')->name('general');
Route::post('/authenticate', 'GeneralPagesController@authenticate')->name('manual_auth');

Auth::routes();

Route::get('/redirect', 'SocialAuthFacebookController@redirect')
  ->name('fb_login');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::resource('pages', 'PageController');
Route::resource('orders', 'OrderController');
Route::resource('pages.coupons', 'CouponController',
  ['only' => ['index', 'show']]
);
Route::post('/add-to-cart', 'CartController@addToCart')
  ->name('add-to-cart');
Route::post('/remove-from-cart', 'CartController@removeFromCart')
  ->name('remove-from-cart');
  Route::get('/cart', 'CartController@index')
    ->name('cart');
Route::post('/coupon_used', 'CouponController@coupon_used')->name('use_coupon');
Route::post('/social_store', 'SocialAuthFacebookController@saveSocialUser')->name('social_store');
Route::get('/social_create', 'SocialAuthFacebookController@createSocialUser')->name('create-social-user');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable= [
      'name',
      'last_name',
      'email',
      'phone',
      'coupon_id',
      'count',
    ];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\Http\Requests\StoreOrder;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrder $request)
    {
        foreach((array)session('cart') as $k => $v)
        {
          $order = new Order;
          $order->name = $request->get('name');
          $order->last_name = $request->get('last_name');
          $order->email = $request->get('email');
          $order->phone = $request->get('phone');
          $order->coupon_id = $k;
          $order->count = $v;
          $order->save();
        }
        session(['cart'=>null]);
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/create.blade.php
@extends('layouts.app')
@section('content')
<div class="request-form">
  <h1>Process order</h1>
  <form class="" action="{{ route('orders.store')}}" method="post">
    {{ csrf_field() }}
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    @guest
      <div class="form-group">
        <label for="">First name</label>
        <input required type="text" name="name" value="" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Last name</label>
        <input required type="text" name="last_name" value="" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Phone</label>
        <input required type="text" name="phone" value="" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Email </label>
        <input required type="text" name="email" value="" class="form-control">
      </div>
    @else
      <div class="form-group">
        <label for="">First name</label>
        <input required type="text" name="name" value="{{ auth()->user()->name }}" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Last name</label>
        <input required type="text" name="last_name" value="{{ auth()->user()->last_name }}" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Phone</label>
        <input required type="text" name="phone" value="{{ auth()->user()->phone }}" class="form-control">
      </div>
      <div class="form-group">
        <label for="">Email </label>
        <input required type="text" name="email" value="{{ auth()->user()->email }}" class="form-control">
      </div>
    @endguest
    <input type="submit" name="" value="Buy" class='btn btn-success'>
  </form>
</div>
@endsection